# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish Package to NuGet

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
  
      - name: Get version info
        uses: dotnet/nbgv@master
        id: nbgv

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "9.0.x"
    
      - name: Pack NuGet (Release)
        run: |
          dotnet pack src/WOLSharp/WOLSharp.csproj \
          -c Release \
          -p:ContinuousIntegrationBuild=true \
          -p:Version=${{ steps.nbgv.outputs.NuGetPackageVersion }} \
          -p:AssemblyVersion=${{ steps.nbgv.outputs.AssemblyVersion }} \
          -p:FileVersion=${{ steps.nbgv.outputs.AssemblyFileVersion }} \
          -o artifacts
          
      - name: NuGet login
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: NuGet Push
        run: dotnet nuget push artifacts/*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
